language: node_js
dist: trusty
node_js:
  - 8
  - 10
matrix:
  allow_failures:
    - node_js: 10
os:
  - linux
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
cache:
  directories:
    - node_modules
before_install:
  - npm i nsp -g
  - npm install -g @angular/cli
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3
install:
  - npm install
script:
  - npm test
#after_script:
#  - nsp check
#  - snyk test
